#libchess: murmur3.c murmur3.h utils.c utils.h position.h chess_context.c chess_context.h game.c game.h
#	clang -Wall -Wextra -O3 -shared -fpic -o libchess.so murmur3.c utils.c game.c chess_context.c
